# **重要注意事项**
# - 本文件必须使用 utf-8 编码
# - 注意中英文标点，例如 '课程序列号: ' 中的冒号为英文冒号
# - 除非必要，尽量保留默认设置

# 用户凭据
username: # TODO
password: # TODO

# 刷新间隔
# - 第一项为时间基数，整数或浮点数，单位为秒，应不小于 3
# - 第二项为随机增量，整数或浮点数，单位为秒，应不小于 1
# - 每次睡眠时间为 rI[0] + rI[1] * random()
refreshInterval:
- 3
- 1

# 请求超时
# - 整数或浮点数，单位为秒，~ 表示不设置，不能为负
requestTimeout: 8

# 重试等待时间
# - 整数或浮点数，单位为秒，不能为 ~ 或负数
retryWaiting: 8

# 候选名单
# - 课程序列号可以唯一匹配
# - 对于同一课程，使用第一匹配
# - 优先级必须为整数，缺省为 1 ，非正优先级将导致候选项被忽略
candidates:

- 课程序列号: BZ2122302335261_18801
  优先级: 2

- 课程名: 《三国志》与三国史

- 课程名: 地震概论
  班号: 1
  优先级: 2
